### ISSUE TITLE
NiftyOne crashes using first command (`participant`)

### ISSUE THREAD

**Issue by nx10** [childmindresearch/niftyone#18]
```
26it [00:00, 97.32it/s, tot=26, good=26, rec=130, err=0]
Traceback (most recent call last):
  File "C:\Users\floru\mambaforge\envs\niftione\lib\site-packages\niclips\figures\multi_view.py", line 197, in slice_video
    writer.put(frame)
  File "C:\Users\floru\mambaforge\envs\niftione\lib\site-packages\niclips\io.py", line 36, in put
    self.init_stream(width=img.width, height=img.height)
  File "C:\Users\floru\mambaforge\envs\niftione\lib\site-packages\niclips\io.py", line 48, in init_stream
    assert isinstance(self._stream, VideoStream)
AssertionError
```

OS: Windows

**Comment by kaitj** [comment]
Thanks! This is probably also good note to set up our actions to run on a matrix of OS's. I'm not sure if gh actions has any MacOS runners (I think maybe the old intel-based ones, not sure about their new M chips). Currently only testing with `ubuntu`.

**Comment by kaitj** [comment]
@nx10 said to close - will reopen if he encounters again
